FROM ubuntu:focal
RUN apt update && apt install curl unzip -y
RUN curl https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip -o ./awscliv2.zip
RUN unzip awscliv2.zip
RUN ./aws/install
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash